dist: bionic
sudo: false
language: cpp
os: linux

matrix:
  include:
    - env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-5
            - lcov

    - env:
      - COMPILER=clang++-7
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - lcov

    - env: COMPILER=g++-8
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-8
            - lcov

before_install:
  # - sudo add-apt-repository -y ppa:samuel-bachmann/boost
  - sudo apt-get -y -d update
install:
  - sudo apt-get -y install cmake ninja-build # libboost-date-time1.60-dev
  - sudo apt-get -y install libboost-all-dev
  - export CXX=${COMPILER}
  - ${CXX} --version
script:
  - ./build_cmake.sh
  - ./test.sh

after_success:
# Create lcov report
- lcov --capture --directory . --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
- lcov --list coverage.info # debug info
# Uploading report to CodeCov
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
