dist: trusty
sudo: false
language: cpp
os: linux

matrix:
  include:
    - env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lcov

    - env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - g++-5
            - lcov

    - env:
      - COMPILER=clang++-7
      - EXERCISM_COMMON_CATCH=false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - lcov

    - env: COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - lcov

before_install:
  # - sudo add-apt-repository -y ppa:samuel-bachmann/boost
  - sudo apt-get -y -d update
install:
  - sudo apt-get -y install cmake3 ninja-build # libboost-date-time1.60-dev
  - sudo apt-get install libboost-all-dev
  - export CXX=${COMPILER}
  - ${CXX} --version
script:
  - ./build_cmake.sh
  - ./test.sh

after_success:
# Create lcov report
- lcov --capture --directory . --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
- lcov --list coverage.info # debug info
# Uploading report to CodeCov
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
