sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
before_install:
- pip install --user cpp-coveralls
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - ./install.sh
  - ./build_cmake.sh
  - ./test.sh
after_success:
  - coveralls --exclude-pattern '*/build/*'
