dist: bionic
language: cpp
os: linux

matrix:
  include:
    - env:
      - COMPILER=clang++-7
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            # - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
            # key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - lcov
    - env: COMPILER=g++-8
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-8
            - lcov

before_install:
  - sudo apt install software-properties-common
  - sudo apt-get -y -d update

install:
  - sudo apt-get -y install cmake ninja-build
  - sudo apt-get -y install libboost-all-dev
  # - sudo pip install codecov
  - sudo apt-get install ggcov gcc-9 g++-9
  - export CXX=${COMPILER}
  - ${CXX} --version
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9

script:
  - ./build_cmake.sh
  - ./test.sh
  # - ./get_code_cov.sh
  # - codecov

after_success:
- find /usr -name gcov
# - bash <(curl -s https://codecov.io/bash)
- lcov --gcov-tool /usr/bin/gcov-9 --capture --directory . --output-file coverage.info
- lcov --gcov-tool /usr/bin/gcov-9 --remove coverage.info '/usr/*' --output-file coverage.info
- lcov --gcov-tool /usr/bin/gcov-9 --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
